### ISSUE TITLE
유저와 프로젝트의 시나리오

### ISSUE THREAD

**Issue by kwangilcho** [wwh-techcamp-2018/team6-SeeYouAtSeptember#1]
유저와 프로젝트 사이에 생길 수 있는 모든 경우의 수에 대해서 상세하게 작성해봅시다.

**Comment by DongHeeYun** [comment]
유저가 프로젝트 작성 페이지의 내용을 모두 작성하고 프로젝트 등록 신청 버튼을 클릭하면 해당 프로젝트가 생성되고 심사중 상태로 저장된다.
  - 심사중인 프로젝트는 자유롭게 수정할 수 있다
  - (심사중인 프로젝트를 일시정지하여 작성중 상태로 변경할 수 있다)

**Comment by chldbtjd2272** [comment]
유저가 프로젝트를 클릭하여 상세보기 페이지로 넘어간 경우
 
1. 프로젝트의 사진 ,영상, 설명을 볼 수 있고 현재 진행되고 있는 상황을 볼 수 있다.
2. 유저가 후원하기 버튼을 누르는 경우
   - 후원하기 페이지로 넘어가 결제 예약을 할 수 있다.


?후원한 프로젝트를 상세보기 눌렀을 경우 후원하기 버튼이 취소하기로 바뀌어야하는가????????????????

**Comment by chldbtjd2272** [comment]
유저(일반유저,게스트유저)가 프로젝트를 클릭하여 모아보기 페이지로 넘어간 경우
    1. 최신순으로 정렬된 프로젝트가 보여진다.
    2. 필터를 통해 다양한 형태로 볼 수 있다.
           - 모금액순으로 정렬
           - 마감 임박순
           - 종료된 프로젝트
