### ISSUE TITLE
카테고리 배지 배너 디자인

### ISSUE THREAD

**Issue by kwangilcho** [wwh-techcamp-2018/team6-SeeYouAtSeptember#11]
[와디즈 리워드 카테고리](https://www.wadiz.kr/web/wreward/category/287)
카테고리별로 간단한 원형 배지 배너를 만들어서 최상단에 띄워주고 있네요.
 
<img width="1192" alt="2018-08-09 12 26 19" src="https://user-images.githubusercontent.com/12382114/43847207-059fafd8-9b6b-11e8-892d-cb15de74ebcc.png">

**Comment by chldbtjd2272** [comment]
카테고리의 깊이가 1단계라서 저희 서비스에 잘 어울릴거 같아요
