### ISSUE TITLE
소셜로그인 구현시 이슈

### ISSUE THREAD

**Issue by chldbtjd2272** [wwh-techcamp-2018/team6-SeeYouAtSeptember#14]
1. rest api만 활용한 백엔드 기반 로그인처리

 2. 자바스크립트와 rest api를 활용하여 프론트와 백엔드를 분리한 로그인처리

[ - 카카오 rest api](https://developers.kakao.com/docs/restapi/usermanagement#%EB%A1%9C%EA%B7%B8%EC%9D%B8)

[ - 카카오 javascript api 클라이언트 기반](https://developers.kakao.com/docs/js/kakaologin)

**Comment by kwangilcho** [comment]
시간이 된다면 타 OAuth도 함께 지원해주면 좋을 것 같습니다.

- [FACEBOOK](https://developers.facebook.com/docs/facebook-login)
- [GOOGLE](https://developers.google.com/identity/protocols/OAuth2)
- [NAVER](https://developers.naver.com/docs/login/overview/)
