### ISSUE TITLE
관리자와 프로젝트의 시나리오

### ISSUE THREAD

**Issue by kwangilcho** [wwh-techcamp-2018/team6-SeeYouAtSeptember#2]
관리자와 프로젝트 사이에 생길 수 있는 모든 경우의 수에 대해서 상세하게 작성해봅시다.

**Comment by mindock** [comment]
관리자는 관리자페이지를 클릭하면, 심사중인 프로젝트의 리스트를 볼 수 있다.

- 프로젝트가 적합한 경우, 게시 상태로 변경한다.
- 프로젝트가 부적합한 경우, 반려 상태로 변경한다.

**Comment by chldbtjd2272** [comment]
관리자를 추가 생성할때.
선택사항
1. 관리자 계정으로 로그인하여 관리자 계정을 회원가입 할 수 있게 한다.
2. 관리자 계정으로 일반유저를 승격시킬 수 있게한다.
