### ISSUE TITLE
Category api 구현 

### ISSUE THREAD

**Issue by chldbtjd2272** [wwh-techcamp-2018/team6-SeeYouAtSeptember#34]
Category api

CATEGORY

~~- 카테고리 전체 목록 조회: GET /api/categories : 카테고리 목록~~
~~- 특정 카테고리 내 프로젝트 전체 조회: GET /api/categories/{cid}~~
~~- 특정 카테고리 내 페이지별 프로젝트 조회: GET /api/categories/{cid}/page/{pageNo}~~

**Comment by mindock** [comment]
CategoryRepository에서 find했을 때 해당 Category가 존재하지 않는 경우, custom exception을 발생해야 한다.
