### ISSUE TITLE
프로젝트 모아보기 레이아웃

### ISSUE THREAD

**Issue by kwangilcho** [wwh-techcamp-2018/team6-SeeYouAtSeptember#4]
팀원 투표를 통해 3단 레이아웃으로 결정되었습니다.
3단 레이아웃과 관련하여 좋은 참조나 아이디어가 있다면 공유해주세요.

**Comment by kwangilcho** [comment]
<img width="1440" alt="2018-08-07 11 46 08" src="https://user-images.githubusercontent.com/12382114/43783277-498b26f2-9a9c-11e8-97e6-9ce14d5359e6.png">

**Comment by kwangilcho** [comment]
[Kickstarter - Technology - Most funded](https://www.kickstarter.com/discover/advanced?category_id=16&woe_id=0&sort=most_funded&seed=2556087&page=2)

<img width="1440" alt="2018-08-07 11 55 49" src="https://user-images.githubusercontent.com/12382114/43783809-8fd881ee-9a9d-11e8-84ef-f69cc276176a.png">

**Comment by mindock** [comment]
[https://storyfunding.daum.net/specialReward]
![kakao](https://user-images.githubusercontent.com/32254667/43788627-e0667fde-9aa8-11e8-9749-7008016fb1bb.JPG)

**Comment by kwangilcho** [comment]
[CSS Grid](https://css-tricks.com/snippets/css/complete-guide-grid/)를 활용하면 깔끔하게 구현할 수 있을 것 같습니다.
