### ISSUE TITLE
project api 구현

### ISSUE THREAD

**Issue by chldbtjd2272** [wwh-techcamp-2018/team6-SeeYouAtSeptember#42]
전체 프로젝트 조회: GET /api/projects 
전체 프로젝트 조회: GET /api/projects/page/{pageNo}
프로젝트 생성: POST /api/projects —> 상세 페이지 url
프로젝트 갱신: PUT /api/projects
프로젝트 삭제: DELETE /api/projects/{pid}

모두 부분완료

1. 로그인 후 모아보기 페이지를 볼때 
   -  프로젝트 정보에 내가 후원한 프로젝트를 다른 프로젝트와 다르게 표시한다.

2. 로그인 후 내가 후원한 프로젝트의 아이디를 세션에 저장한다.

**Comment by chldbtjd2272** [comment]
프로젝트 목록을 던져줄때 product에 대한 후원 양을 계산하여 같이 던져주도록 바꿔야한다.

**Comment by kwangilcho** [comment]
product에 대해서 몇명이 현재 후원하고 있는지를 productUserMap을 통해서 productDTO에 담고,
프로젝트에서는 productDTO들을 통해서 전체 후원 금액을 계산하여 담아 반환합니다.

**Comment by kwangilcho** [comment]
구현 완료 #70
