### ISSUE TITLE
BaseTimeEntity 와 Project의관계

### ISSUE THREAD

**Issue by chldbtjd2272** [wwh-techcamp-2018/team6-SeeYouAtSeptember#43]
baseTimeEntity를 상속받은 Project를 생성할때 createTime컬럼이 project테이블 안에 생깁니다.

startAt컬럼과 createTime의 컬럼이 중첩된 역할을 하고 있기때문에 한가지는 제거해야 할 것 같습니다.

**Comment by kwangilcho** [comment]
적용 완료 되었습니다.
