### ISSUE TITLE
프로젝트 삭제와 수정에대한 이슈

### ISSUE THREAD

**Issue by DongHeeYun** [wwh-techcamp-2018/team6-SeeYouAtSeptember#45]
프로젝트 삭제시 deleted플래그를 사용하는 방식으로 변경

프로젝트 삭제시 프로덕트도 삭제할 수 있도록 변경(프로덕트도 deleted플래그)

프로젝트 수정시 프로덕트를 따로 수정할지 같이 수정할지 결정해야함

**Comment by kwangilcho** [comment]
deleted를 사용중입니다.
수정은 불가능!
