### ISSUE TITLE
프로젝트 상세 레이아웃

### ISSUE THREAD

**Issue by kwangilcho** [wwh-techcamp-2018/team6-SeeYouAtSeptember#5]
프로젝트 상세페이지와 관련하여 좋은 참조나 아이디어가 있다면 공유해주세요.

**Comment by kwangilcho** [comment]
킥스타터 프로젝트 상세 레이아웃

<img width="1440" alt="2018-08-07 11 52 03" src="https://user-images.githubusercontent.com/12382114/43783952-ef0b70b8-9a9d-11e8-8c76-7d2e348ac0c5.png">
<img width="1440" alt="2018-08-07 11 52 10" src="https://user-images.githubusercontent.com/12382114/43783953-ef3ecd50-9a9d-11e8-86db-c1e21cf1194b.png">

**Comment by kwangilcho** [comment]
텀블벅 프로젝트 상세 레이아웃

<img width="1440" alt="2018-08-07 11 51 45" src="https://user-images.githubusercontent.com/12382114/43784049-2c756e5e-9a9e-11e8-9809-67458bf6d137.png">
<img width="1440" alt="2018-08-07 11 51 51" src="https://user-images.githubusercontent.com/12382114/43784050-2cb78014-9a9e-11e8-9422-df69e1e51daf.png">

**Comment by kwangilcho** [comment]
와디즈 프로젝트 상세 레이아웃

<img width="1440" alt="2018-08-07 11 51 13" src="https://user-images.githubusercontent.com/12382114/43784193-78dbeb1a-9a9e-11e8-8485-58b11dff3558.png">
<img width="1440" alt="2018-08-07 11 51 18" src="https://user-images.githubusercontent.com/12382114/43784194-79016e44-9a9e-11e8-9c4f-c0d44f657183.png">

**Comment by kwangilcho** [comment]
크라우디 프로젝트 상세 레이아웃

<img width="1440" alt="2018-08-07 11 50 53" src="https://user-images.githubusercontent.com/12382114/43784285-b39262de-9a9e-11e8-8a98-b11dd094f782.png">
<img width="1440" alt="2018-08-07 11 50 59" src="https://user-images.githubusercontent.com/12382114/43784286-b3be4ac0-9a9e-11e8-8733-f8b57e88c5f9.png">

**Comment by chldbtjd2272** [comment]
텀블벅 회원가입 창
<img width="1440" alt="2018-08-08 12 33 53" src="https://user-images.githubusercontent.com/25260024/43786119-de39bad8-9aa2-11e8-846a-4907a095745c.png">

**Comment by chldbtjd2272** [comment]
텀블벅 회원가입 창
<img width="1440" alt="2018-08-08 12 34 11" src="https://user-images.githubusercontent.com/25260024/43786174-016ca754-9aa3-11e8-83f8-3666322a7b58.png">

**Comment by chldbtjd2272** [comment]
와디즈 로그인 창
<img width="1428" alt="2018-08-08 12 33 04" src="https://user-images.githubusercontent.com/25260024/43786225-1cb609f6-9aa3-11e8-9330-2c13d1134fd8.png">

**Comment by chldbtjd2272** [comment]
와디즈 회원가입 창
<img width="1440" alt="2018-08-08 12 33 34" src="https://user-images.githubusercontent.com/25260024/43786242-26c51252-9aa3-11e8-9c95-e38d051c0dc1.png">

**Comment by mindock** [comment]
오마이컴퍼니 프로젝트 상세 레이아웃
![image](https://user-images.githubusercontent.com/32254667/43789341-aeb7cebe-9aaa-11e8-9c52-b1e3b0049c57.png)
![image](https://user-images.githubusercontent.com/32254667/43789392-d3b2a3c4-9aaa-11e8-8c7b-8e9b3c3eb5b5.png)
