### ISSUE TITLE
프로젝트 모아보기 캐시

### ISSUE THREAD

**Issue by chldbtjd2272** [wwh-techcamp-2018/team6-SeeYouAtSeptember#50]
프로젝트 모아보기 api에서 카테고리별 데이터를 캐시해 놓고 뿌려주는 형태인데,
실시간으로 변하는 프로그래스바 때문에 프로그래스바 데이터는 따로 ajax통신을 해서 받아와야할 것 같습니다.

2주차 개발에서 웹소켓이나 mqtt를 적용하여 해결해야합니다!.

**Comment by kwangilcho** [comment]
MQTT 적용은 sprint2로 넘기겠습니다.
