### ISSUE TITLE
[버그] 회원가입할때 비밀번호 영문/숫자 8자리인데 형식을 확인하라고 해요ㅠ

### ISSUE THREAD

**Issue by kimyeon0331** [wwh-techcamp-2018/team6-SeeYouAtSeptember#83]
<img width="1180" alt="2018-08-24 5 05 28" src="https://user-images.githubusercontent.com/19780879/44572868-143e8080-a7c0-11e8-8976-867307c85c36.png">

**Comment by kwangilcho** [comment]
감사합니다! 피드백 반영하겠습니다.
비밀번호 양식에 대해서 조금 더 친절하게 안내하도록 하겠습니다.
