### ISSUE TITLE
[kwonhyoena] 더보기 버튼

### ISSUE THREAD

**Issue by kwonhyeona** [wwh-techcamp-2018/team6-SeeYouAtSeptember#84]
더보기 버튼을 눌렀는데 내용이 안나오네욤ㅠㅠㅠ더 받아올 내용이 없는건가..?

**Comment by kwangilcho** [comment]
감사합니다! 피드백 반영하겠습니다.
더 이상 받아올 것이 없을 땐 더보기가 사라지게 만들게요 :-)
