### ISSUE TITLE
사용자 입장에서 요청사항 입니다.

### ISSUE THREAD

**Issue by serverwizard** [wwh-techcamp-2018/team6-SeeYouAtSeptember#87]
'물품 추가' 버튼을 누른 다음, '물품 빼기' 누르고 다시 '물품 추가' 버튼 눌러도
작성했던 내용이 유지됐으면 좋겠어요(실수로 물품빼기를 누를 수도 있잖아요)
잘봤습니다!! ^^

**Comment by serverwizard** [comment]
파일 첨부 시, 이미지 확장자가 아닌 파일을 첨부 했을 때 경고 메세지가 안떠요.

**Comment by kwangilcho** [comment]
감사합니다. 피드백 반영하였습니다.
