### ISSUE TITLE
후원목록을 많이 등록하면 무한스크롤입니다.

### ISSUE THREAD

**Issue by songintae** [wwh-techcamp-2018/team6-SeeYouAtSeptember#88]
<img width="1240" alt="2018-08-24 5 16 28" src="https://user-images.githubusercontent.com/19792798/44573403-7d72c380-a7c1-11e8-9bb0-8c924ef31d6c.png">

**Comment by kwangilcho** [comment]
감사합니다! 피드백 반영하겠습니다.
에러는 아니고, 하나의 프로젝트에 너무 많은 후원목록이 달려있어서 그런 것 같아요.
갯수 제한을 두고 관리하겠습니다. :-)
