### ISSUE TITLE
원형 이미지가 눌려보입니다

### ISSUE THREAD

**Issue by jhyang12345** [wwh-techcamp-2018/team6-SeeYouAtSeptember#89]
원형 이미지 옆으로 늘어나 보여요!! 옆부분을 자르고 센터링 해야할것 같아요

**Comment by kwangilcho** [comment]
감사합니다!
사용자에게 받은 이미지를 고정 비율로 크롭하게 UI/UX를 구성하여 피드백 반영하였습니다.
