### ISSUE TITLE
회원가입 오류

### ISSUE THREAD

**Issue by hyukjin-lee** [wwh-techcamp-2018/team6-SeeYouAtSeptember#90]
Validation 처리가 제대로 안된 것 같습니다.
이메일 칸에 @를 입력해도 가입이되고, 이름도 엄청 길게 써도 가입이 됩니다

**Comment by kwangilcho** [comment]
감사합니다. 피드백 반영하겠습니다!

**Comment by kwangilcho** [comment]
피드백 반영했습니다.
