### ISSUE TITLE
회원가입, 유저정보 반환

### ISSUE THREAD

**Issue by ParkJuha** [wwh-techcamp-2018/team6-SeeYouAtSeptember#92]
회원가입 할 때 아이디 중복에 대해 알림이 있었으면 좋겠네요!^^
http://54.180.46.248:8080/api/users 를 하니깐 유저 정보가 넘어오네요 ㅠㅠ! 

6팀 화이팅

**Comment by kwangilcho** [comment]
아이코, 큰 일 날 뻔 했네요.
감사합니다. 피드백 반영하였습니다!
