### ISSUE TITLE
이상한 부분에서 클릭하면 로그인 이동

### ISSUE THREAD

**Issue by dain7672** [wwh-techcamp-2018/team6-SeeYouAtSeptember#93]
![image](https://user-images.githubusercontent.com/29906076/44574049-31288300-a7c3-11e8-8a33-3b09f66dca84.png)
여기서 필 글자 부분 근처를 누르면 로그인으로 이동해요

**Comment by kwangilcho** [comment]
감사합니다! 피드백 반영하겠습니다.

**Comment by DongHeeYun** [comment]
반영 완료했습니다!
